# Generated by Django 2.0.5 on 2019-09-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daiban', models.CharField(max_length=255)),
                ('yiwancheng', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='wenzhang',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('text2', models.CharField(max_length=200)),
                ('text3', models.CharField(max_length=200)),
            ],
        ),
    ]
