# Generated by Django 2.0.5 on 2019-09-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wenzhang',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='wenzhang',
            name='text3',
        ),
    ]
